import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const animals = sqliteTable('animals', {
  id: text('id').primaryKey(),
  desertionNo: text('desertionNo').unique().notNull(),
  animalRegistrationNo: text('animalRegistrationNo'),
  breed: text('breed'),
  gender: text('gender'),
  color: text('color'),
  neutered: text('neutered'),
  age: text('age'),
  weight: text('weight'),
  rescueFeatures: text('rescueFeatures'),
  socialTraits: text('socialTraits'),
  healthTraits: text('healthTraits'),
  healthCheck: text('healthCheck'),
  vaccination: text('vaccination'),
  location: text('location'),
  receivedDate: text('receivedDate'),
  notes: text('notes'),
  jurisdiction: text('jurisdiction'),
  status: text('status'),
  shelterName: text('shelterName'),
  shelterLocation: text('shelterLocation'),
  shelterContact: text('shelterContact'),
  adoptionProcess: text('adoptionProcess'),
  adoptionSupport: text('adoptionSupport'),
  volunteerInfo: text('volunteerInfo'),
  eventInfo: text('eventInfo'),
  photo: text('photo'),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull(),
});
